// Code generated by ent, DO NOT EDIT.

package twitchcategory

import (
	"time"

	"entgo.io/ent/dialect/sql"
)

const (
	// Label holds the string label denoting the twitchcategory type in the database.
	Label = "twitch_category"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldName holds the string denoting the name field in the database.
	FieldName = "name"
	// FieldBoxArtURL holds the string denoting the box_art_url field in the database.
	FieldBoxArtURL = "box_art_url"
	// FieldIgdbID holds the string denoting the igdb_id field in the database.
	FieldIgdbID = "igdb_id"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// Table holds the table name of the twitchcategory in the database.
	Table = "twitch_categories"
)

// Columns holds all SQL columns for twitchcategory fields.
var Columns = []string{
	FieldID,
	FieldName,
	FieldBoxArtURL,
	FieldIgdbID,
	FieldUpdatedAt,
	FieldCreatedAt,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultUpdatedAt holds the default value on creation for the "updated_at" field.
	DefaultUpdatedAt func() time.Time
	// UpdateDefaultUpdatedAt holds the default value on update for the "updated_at" field.
	UpdateDefaultUpdatedAt func() time.Time
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
)

// OrderOption defines the ordering options for the TwitchCategory queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByName orders the results by the name field.
func ByName(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldName, opts...).ToFunc()
}

// ByBoxArtURL orders the results by the box_art_url field.
func ByBoxArtURL(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldBoxArtURL, opts...).ToFunc()
}

// ByIgdbID orders the results by the igdb_id field.
func ByIgdbID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldIgdbID, opts...).ToFunc()
}

// ByUpdatedAt orders the results by the updated_at field.
func ByUpdatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdatedAt, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}
