import '@mantine/core/styles.css';
import '@mantine/notifications/styles.css';
import 'mantine-datatable/styles.layer.css';
import '@/app/global.css'

import { ColorSchemeScript } from '@mantine/core';
import type { Metadata } from "next";
import Providers from './providers';
import { PublicEnvScript } from 'next-runtime-env';

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  return (
    <html lang="en" suppressHydrationWarning>
      <head>
        <PublicEnvScript />
        <ColorSchemeScript />
      </head>
      <body>

        <Providers>
          {children}
        </Providers>

      </body>
    </html>
  );
}
