// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
	"github.com/zibbp/ganymede/ent/channel"
	"github.com/zibbp/ganymede/ent/live"
	"github.com/zibbp/ganymede/ent/predicate"
	"github.com/zibbp/ganymede/ent/vod"
)

// ChannelUpdate is the builder for updating Channel entities.
type ChannelUpdate struct {
	config
	hooks    []Hook
	mutation *ChannelMutation
}

// Where appends a list predicates to the ChannelUpdate builder.
func (_u *ChannelUpdate) Where(ps ...predicate.Channel) *ChannelUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetExtID sets the "ext_id" field.
func (_u *ChannelUpdate) SetExtID(v string) *ChannelUpdate {
	_u.mutation.SetExtID(v)
	return _u
}

// SetNillableExtID sets the "ext_id" field if the given value is not nil.
func (_u *ChannelUpdate) SetNillableExtID(v *string) *ChannelUpdate {
	if v != nil {
		_u.SetExtID(*v)
	}
	return _u
}

// ClearExtID clears the value of the "ext_id" field.
func (_u *ChannelUpdate) ClearExtID() *ChannelUpdate {
	_u.mutation.ClearExtID()
	return _u
}

// SetName sets the "name" field.
func (_u *ChannelUpdate) SetName(v string) *ChannelUpdate {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *ChannelUpdate) SetNillableName(v *string) *ChannelUpdate {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetDisplayName sets the "display_name" field.
func (_u *ChannelUpdate) SetDisplayName(v string) *ChannelUpdate {
	_u.mutation.SetDisplayName(v)
	return _u
}

// SetNillableDisplayName sets the "display_name" field if the given value is not nil.
func (_u *ChannelUpdate) SetNillableDisplayName(v *string) *ChannelUpdate {
	if v != nil {
		_u.SetDisplayName(*v)
	}
	return _u
}

// SetImagePath sets the "image_path" field.
func (_u *ChannelUpdate) SetImagePath(v string) *ChannelUpdate {
	_u.mutation.SetImagePath(v)
	return _u
}

// SetNillableImagePath sets the "image_path" field if the given value is not nil.
func (_u *ChannelUpdate) SetNillableImagePath(v *string) *ChannelUpdate {
	if v != nil {
		_u.SetImagePath(*v)
	}
	return _u
}

// SetRetention sets the "retention" field.
func (_u *ChannelUpdate) SetRetention(v bool) *ChannelUpdate {
	_u.mutation.SetRetention(v)
	return _u
}

// SetNillableRetention sets the "retention" field if the given value is not nil.
func (_u *ChannelUpdate) SetNillableRetention(v *bool) *ChannelUpdate {
	if v != nil {
		_u.SetRetention(*v)
	}
	return _u
}

// SetRetentionDays sets the "retention_days" field.
func (_u *ChannelUpdate) SetRetentionDays(v int64) *ChannelUpdate {
	_u.mutation.ResetRetentionDays()
	_u.mutation.SetRetentionDays(v)
	return _u
}

// SetNillableRetentionDays sets the "retention_days" field if the given value is not nil.
func (_u *ChannelUpdate) SetNillableRetentionDays(v *int64) *ChannelUpdate {
	if v != nil {
		_u.SetRetentionDays(*v)
	}
	return _u
}

// AddRetentionDays adds value to the "retention_days" field.
func (_u *ChannelUpdate) AddRetentionDays(v int64) *ChannelUpdate {
	_u.mutation.AddRetentionDays(v)
	return _u
}

// ClearRetentionDays clears the value of the "retention_days" field.
func (_u *ChannelUpdate) ClearRetentionDays() *ChannelUpdate {
	_u.mutation.ClearRetentionDays()
	return _u
}

// SetStorageSizeBytes sets the "storage_size_bytes" field.
func (_u *ChannelUpdate) SetStorageSizeBytes(v int64) *ChannelUpdate {
	_u.mutation.ResetStorageSizeBytes()
	_u.mutation.SetStorageSizeBytes(v)
	return _u
}

// SetNillableStorageSizeBytes sets the "storage_size_bytes" field if the given value is not nil.
func (_u *ChannelUpdate) SetNillableStorageSizeBytes(v *int64) *ChannelUpdate {
	if v != nil {
		_u.SetStorageSizeBytes(*v)
	}
	return _u
}

// AddStorageSizeBytes adds value to the "storage_size_bytes" field.
func (_u *ChannelUpdate) AddStorageSizeBytes(v int64) *ChannelUpdate {
	_u.mutation.AddStorageSizeBytes(v)
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *ChannelUpdate) SetUpdatedAt(v time.Time) *ChannelUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// AddVodIDs adds the "vods" edge to the Vod entity by IDs.
func (_u *ChannelUpdate) AddVodIDs(ids ...uuid.UUID) *ChannelUpdate {
	_u.mutation.AddVodIDs(ids...)
	return _u
}

// AddVods adds the "vods" edges to the Vod entity.
func (_u *ChannelUpdate) AddVods(v ...*Vod) *ChannelUpdate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddVodIDs(ids...)
}

// AddLiveIDs adds the "live" edge to the Live entity by IDs.
func (_u *ChannelUpdate) AddLiveIDs(ids ...uuid.UUID) *ChannelUpdate {
	_u.mutation.AddLiveIDs(ids...)
	return _u
}

// AddLive adds the "live" edges to the Live entity.
func (_u *ChannelUpdate) AddLive(v ...*Live) *ChannelUpdate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddLiveIDs(ids...)
}

// Mutation returns the ChannelMutation object of the builder.
func (_u *ChannelUpdate) Mutation() *ChannelMutation {
	return _u.mutation
}

// ClearVods clears all "vods" edges to the Vod entity.
func (_u *ChannelUpdate) ClearVods() *ChannelUpdate {
	_u.mutation.ClearVods()
	return _u
}

// RemoveVodIDs removes the "vods" edge to Vod entities by IDs.
func (_u *ChannelUpdate) RemoveVodIDs(ids ...uuid.UUID) *ChannelUpdate {
	_u.mutation.RemoveVodIDs(ids...)
	return _u
}

// RemoveVods removes "vods" edges to Vod entities.
func (_u *ChannelUpdate) RemoveVods(v ...*Vod) *ChannelUpdate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveVodIDs(ids...)
}

// ClearLive clears all "live" edges to the Live entity.
func (_u *ChannelUpdate) ClearLive() *ChannelUpdate {
	_u.mutation.ClearLive()
	return _u
}

// RemoveLiveIDs removes the "live" edge to Live entities by IDs.
func (_u *ChannelUpdate) RemoveLiveIDs(ids ...uuid.UUID) *ChannelUpdate {
	_u.mutation.RemoveLiveIDs(ids...)
	return _u
}

// RemoveLive removes "live" edges to Live entities.
func (_u *ChannelUpdate) RemoveLive(v ...*Live) *ChannelUpdate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveLiveIDs(ids...)
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *ChannelUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *ChannelUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *ChannelUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *ChannelUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *ChannelUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := channel.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

func (_u *ChannelUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	_spec := sqlgraph.NewUpdateSpec(channel.Table, channel.Columns, sqlgraph.NewFieldSpec(channel.FieldID, field.TypeUUID))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.ExtID(); ok {
		_spec.SetField(channel.FieldExtID, field.TypeString, value)
	}
	if _u.mutation.ExtIDCleared() {
		_spec.ClearField(channel.FieldExtID, field.TypeString)
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(channel.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.DisplayName(); ok {
		_spec.SetField(channel.FieldDisplayName, field.TypeString, value)
	}
	if value, ok := _u.mutation.ImagePath(); ok {
		_spec.SetField(channel.FieldImagePath, field.TypeString, value)
	}
	if value, ok := _u.mutation.Retention(); ok {
		_spec.SetField(channel.FieldRetention, field.TypeBool, value)
	}
	if value, ok := _u.mutation.RetentionDays(); ok {
		_spec.SetField(channel.FieldRetentionDays, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedRetentionDays(); ok {
		_spec.AddField(channel.FieldRetentionDays, field.TypeInt64, value)
	}
	if _u.mutation.RetentionDaysCleared() {
		_spec.ClearField(channel.FieldRetentionDays, field.TypeInt64)
	}
	if value, ok := _u.mutation.StorageSizeBytes(); ok {
		_spec.SetField(channel.FieldStorageSizeBytes, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedStorageSizeBytes(); ok {
		_spec.AddField(channel.FieldStorageSizeBytes, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(channel.FieldUpdatedAt, field.TypeTime, value)
	}
	if _u.mutation.VodsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   channel.VodsTable,
			Columns: []string{channel.VodsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(vod.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedVodsIDs(); len(nodes) > 0 && !_u.mutation.VodsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   channel.VodsTable,
			Columns: []string{channel.VodsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(vod.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.VodsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   channel.VodsTable,
			Columns: []string{channel.VodsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(vod.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.LiveCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   channel.LiveTable,
			Columns: []string{channel.LiveColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(live.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedLiveIDs(); len(nodes) > 0 && !_u.mutation.LiveCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   channel.LiveTable,
			Columns: []string{channel.LiveColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(live.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.LiveIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   channel.LiveTable,
			Columns: []string{channel.LiveColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(live.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{channel.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// ChannelUpdateOne is the builder for updating a single Channel entity.
type ChannelUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *ChannelMutation
}

// SetExtID sets the "ext_id" field.
func (_u *ChannelUpdateOne) SetExtID(v string) *ChannelUpdateOne {
	_u.mutation.SetExtID(v)
	return _u
}

// SetNillableExtID sets the "ext_id" field if the given value is not nil.
func (_u *ChannelUpdateOne) SetNillableExtID(v *string) *ChannelUpdateOne {
	if v != nil {
		_u.SetExtID(*v)
	}
	return _u
}

// ClearExtID clears the value of the "ext_id" field.
func (_u *ChannelUpdateOne) ClearExtID() *ChannelUpdateOne {
	_u.mutation.ClearExtID()
	return _u
}

// SetName sets the "name" field.
func (_u *ChannelUpdateOne) SetName(v string) *ChannelUpdateOne {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *ChannelUpdateOne) SetNillableName(v *string) *ChannelUpdateOne {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetDisplayName sets the "display_name" field.
func (_u *ChannelUpdateOne) SetDisplayName(v string) *ChannelUpdateOne {
	_u.mutation.SetDisplayName(v)
	return _u
}

// SetNillableDisplayName sets the "display_name" field if the given value is not nil.
func (_u *ChannelUpdateOne) SetNillableDisplayName(v *string) *ChannelUpdateOne {
	if v != nil {
		_u.SetDisplayName(*v)
	}
	return _u
}

// SetImagePath sets the "image_path" field.
func (_u *ChannelUpdateOne) SetImagePath(v string) *ChannelUpdateOne {
	_u.mutation.SetImagePath(v)
	return _u
}

// SetNillableImagePath sets the "image_path" field if the given value is not nil.
func (_u *ChannelUpdateOne) SetNillableImagePath(v *string) *ChannelUpdateOne {
	if v != nil {
		_u.SetImagePath(*v)
	}
	return _u
}

// SetRetention sets the "retention" field.
func (_u *ChannelUpdateOne) SetRetention(v bool) *ChannelUpdateOne {
	_u.mutation.SetRetention(v)
	return _u
}

// SetNillableRetention sets the "retention" field if the given value is not nil.
func (_u *ChannelUpdateOne) SetNillableRetention(v *bool) *ChannelUpdateOne {
	if v != nil {
		_u.SetRetention(*v)
	}
	return _u
}

// SetRetentionDays sets the "retention_days" field.
func (_u *ChannelUpdateOne) SetRetentionDays(v int64) *ChannelUpdateOne {
	_u.mutation.ResetRetentionDays()
	_u.mutation.SetRetentionDays(v)
	return _u
}

// SetNillableRetentionDays sets the "retention_days" field if the given value is not nil.
func (_u *ChannelUpdateOne) SetNillableRetentionDays(v *int64) *ChannelUpdateOne {
	if v != nil {
		_u.SetRetentionDays(*v)
	}
	return _u
}

// AddRetentionDays adds value to the "retention_days" field.
func (_u *ChannelUpdateOne) AddRetentionDays(v int64) *ChannelUpdateOne {
	_u.mutation.AddRetentionDays(v)
	return _u
}

// ClearRetentionDays clears the value of the "retention_days" field.
func (_u *ChannelUpdateOne) ClearRetentionDays() *ChannelUpdateOne {
	_u.mutation.ClearRetentionDays()
	return _u
}

// SetStorageSizeBytes sets the "storage_size_bytes" field.
func (_u *ChannelUpdateOne) SetStorageSizeBytes(v int64) *ChannelUpdateOne {
	_u.mutation.ResetStorageSizeBytes()
	_u.mutation.SetStorageSizeBytes(v)
	return _u
}

// SetNillableStorageSizeBytes sets the "storage_size_bytes" field if the given value is not nil.
func (_u *ChannelUpdateOne) SetNillableStorageSizeBytes(v *int64) *ChannelUpdateOne {
	if v != nil {
		_u.SetStorageSizeBytes(*v)
	}
	return _u
}

// AddStorageSizeBytes adds value to the "storage_size_bytes" field.
func (_u *ChannelUpdateOne) AddStorageSizeBytes(v int64) *ChannelUpdateOne {
	_u.mutation.AddStorageSizeBytes(v)
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *ChannelUpdateOne) SetUpdatedAt(v time.Time) *ChannelUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// AddVodIDs adds the "vods" edge to the Vod entity by IDs.
func (_u *ChannelUpdateOne) AddVodIDs(ids ...uuid.UUID) *ChannelUpdateOne {
	_u.mutation.AddVodIDs(ids...)
	return _u
}

// AddVods adds the "vods" edges to the Vod entity.
func (_u *ChannelUpdateOne) AddVods(v ...*Vod) *ChannelUpdateOne {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddVodIDs(ids...)
}

// AddLiveIDs adds the "live" edge to the Live entity by IDs.
func (_u *ChannelUpdateOne) AddLiveIDs(ids ...uuid.UUID) *ChannelUpdateOne {
	_u.mutation.AddLiveIDs(ids...)
	return _u
}

// AddLive adds the "live" edges to the Live entity.
func (_u *ChannelUpdateOne) AddLive(v ...*Live) *ChannelUpdateOne {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddLiveIDs(ids...)
}

// Mutation returns the ChannelMutation object of the builder.
func (_u *ChannelUpdateOne) Mutation() *ChannelMutation {
	return _u.mutation
}

// ClearVods clears all "vods" edges to the Vod entity.
func (_u *ChannelUpdateOne) ClearVods() *ChannelUpdateOne {
	_u.mutation.ClearVods()
	return _u
}

// RemoveVodIDs removes the "vods" edge to Vod entities by IDs.
func (_u *ChannelUpdateOne) RemoveVodIDs(ids ...uuid.UUID) *ChannelUpdateOne {
	_u.mutation.RemoveVodIDs(ids...)
	return _u
}

// RemoveVods removes "vods" edges to Vod entities.
func (_u *ChannelUpdateOne) RemoveVods(v ...*Vod) *ChannelUpdateOne {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveVodIDs(ids...)
}

// ClearLive clears all "live" edges to the Live entity.
func (_u *ChannelUpdateOne) ClearLive() *ChannelUpdateOne {
	_u.mutation.ClearLive()
	return _u
}

// RemoveLiveIDs removes the "live" edge to Live entities by IDs.
func (_u *ChannelUpdateOne) RemoveLiveIDs(ids ...uuid.UUID) *ChannelUpdateOne {
	_u.mutation.RemoveLiveIDs(ids...)
	return _u
}

// RemoveLive removes "live" edges to Live entities.
func (_u *ChannelUpdateOne) RemoveLive(v ...*Live) *ChannelUpdateOne {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveLiveIDs(ids...)
}

// Where appends a list predicates to the ChannelUpdate builder.
func (_u *ChannelUpdateOne) Where(ps ...predicate.Channel) *ChannelUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *ChannelUpdateOne) Select(field string, fields ...string) *ChannelUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated Channel entity.
func (_u *ChannelUpdateOne) Save(ctx context.Context) (*Channel, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *ChannelUpdateOne) SaveX(ctx context.Context) *Channel {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *ChannelUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *ChannelUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *ChannelUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := channel.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

func (_u *ChannelUpdateOne) sqlSave(ctx context.Context) (_node *Channel, err error) {
	_spec := sqlgraph.NewUpdateSpec(channel.Table, channel.Columns, sqlgraph.NewFieldSpec(channel.FieldID, field.TypeUUID))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Channel.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, channel.FieldID)
		for _, f := range fields {
			if !channel.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != channel.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.ExtID(); ok {
		_spec.SetField(channel.FieldExtID, field.TypeString, value)
	}
	if _u.mutation.ExtIDCleared() {
		_spec.ClearField(channel.FieldExtID, field.TypeString)
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(channel.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.DisplayName(); ok {
		_spec.SetField(channel.FieldDisplayName, field.TypeString, value)
	}
	if value, ok := _u.mutation.ImagePath(); ok {
		_spec.SetField(channel.FieldImagePath, field.TypeString, value)
	}
	if value, ok := _u.mutation.Retention(); ok {
		_spec.SetField(channel.FieldRetention, field.TypeBool, value)
	}
	if value, ok := _u.mutation.RetentionDays(); ok {
		_spec.SetField(channel.FieldRetentionDays, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedRetentionDays(); ok {
		_spec.AddField(channel.FieldRetentionDays, field.TypeInt64, value)
	}
	if _u.mutation.RetentionDaysCleared() {
		_spec.ClearField(channel.FieldRetentionDays, field.TypeInt64)
	}
	if value, ok := _u.mutation.StorageSizeBytes(); ok {
		_spec.SetField(channel.FieldStorageSizeBytes, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedStorageSizeBytes(); ok {
		_spec.AddField(channel.FieldStorageSizeBytes, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(channel.FieldUpdatedAt, field.TypeTime, value)
	}
	if _u.mutation.VodsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   channel.VodsTable,
			Columns: []string{channel.VodsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(vod.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedVodsIDs(); len(nodes) > 0 && !_u.mutation.VodsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   channel.VodsTable,
			Columns: []string{channel.VodsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(vod.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.VodsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   channel.VodsTable,
			Columns: []string{channel.VodsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(vod.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.LiveCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   channel.LiveTable,
			Columns: []string{channel.LiveColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(live.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedLiveIDs(); len(nodes) > 0 && !_u.mutation.LiveCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   channel.LiveTable,
			Columns: []string{channel.LiveColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(live.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.LiveIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   channel.LiveTable,
			Columns: []string{channel.LiveColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(live.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &Channel{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{channel.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
