// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
	"github.com/zibbp/ganymede/ent/live"
	"github.com/zibbp/ganymede/ent/livecategory"
	"github.com/zibbp/ganymede/ent/predicate"
)

// LiveCategoryUpdate is the builder for updating LiveCategory entities.
type LiveCategoryUpdate struct {
	config
	hooks    []Hook
	mutation *LiveCategoryMutation
}

// Where appends a list predicates to the LiveCategoryUpdate builder.
func (_u *LiveCategoryUpdate) Where(ps ...predicate.LiveCategory) *LiveCategoryUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetName sets the "name" field.
func (_u *LiveCategoryUpdate) SetName(v string) *LiveCategoryUpdate {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *LiveCategoryUpdate) SetNillableName(v *string) *LiveCategoryUpdate {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// ClearName clears the value of the "name" field.
func (_u *LiveCategoryUpdate) ClearName() *LiveCategoryUpdate {
	_u.mutation.ClearName()
	return _u
}

// SetLiveID sets the "live" edge to the Live entity by ID.
func (_u *LiveCategoryUpdate) SetLiveID(id uuid.UUID) *LiveCategoryUpdate {
	_u.mutation.SetLiveID(id)
	return _u
}

// SetLive sets the "live" edge to the Live entity.
func (_u *LiveCategoryUpdate) SetLive(v *Live) *LiveCategoryUpdate {
	return _u.SetLiveID(v.ID)
}

// Mutation returns the LiveCategoryMutation object of the builder.
func (_u *LiveCategoryUpdate) Mutation() *LiveCategoryMutation {
	return _u.mutation
}

// ClearLive clears the "live" edge to the Live entity.
func (_u *LiveCategoryUpdate) ClearLive() *LiveCategoryUpdate {
	_u.mutation.ClearLive()
	return _u
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *LiveCategoryUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *LiveCategoryUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *LiveCategoryUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *LiveCategoryUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *LiveCategoryUpdate) check() error {
	if _u.mutation.LiveCleared() && len(_u.mutation.LiveIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "LiveCategory.live"`)
	}
	return nil
}

func (_u *LiveCategoryUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(livecategory.Table, livecategory.Columns, sqlgraph.NewFieldSpec(livecategory.FieldID, field.TypeUUID))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(livecategory.FieldName, field.TypeString, value)
	}
	if _u.mutation.NameCleared() {
		_spec.ClearField(livecategory.FieldName, field.TypeString)
	}
	if _u.mutation.LiveCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   livecategory.LiveTable,
			Columns: []string{livecategory.LiveColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(live.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.LiveIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   livecategory.LiveTable,
			Columns: []string{livecategory.LiveColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(live.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{livecategory.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// LiveCategoryUpdateOne is the builder for updating a single LiveCategory entity.
type LiveCategoryUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *LiveCategoryMutation
}

// SetName sets the "name" field.
func (_u *LiveCategoryUpdateOne) SetName(v string) *LiveCategoryUpdateOne {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *LiveCategoryUpdateOne) SetNillableName(v *string) *LiveCategoryUpdateOne {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// ClearName clears the value of the "name" field.
func (_u *LiveCategoryUpdateOne) ClearName() *LiveCategoryUpdateOne {
	_u.mutation.ClearName()
	return _u
}

// SetLiveID sets the "live" edge to the Live entity by ID.
func (_u *LiveCategoryUpdateOne) SetLiveID(id uuid.UUID) *LiveCategoryUpdateOne {
	_u.mutation.SetLiveID(id)
	return _u
}

// SetLive sets the "live" edge to the Live entity.
func (_u *LiveCategoryUpdateOne) SetLive(v *Live) *LiveCategoryUpdateOne {
	return _u.SetLiveID(v.ID)
}

// Mutation returns the LiveCategoryMutation object of the builder.
func (_u *LiveCategoryUpdateOne) Mutation() *LiveCategoryMutation {
	return _u.mutation
}

// ClearLive clears the "live" edge to the Live entity.
func (_u *LiveCategoryUpdateOne) ClearLive() *LiveCategoryUpdateOne {
	_u.mutation.ClearLive()
	return _u
}

// Where appends a list predicates to the LiveCategoryUpdate builder.
func (_u *LiveCategoryUpdateOne) Where(ps ...predicate.LiveCategory) *LiveCategoryUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *LiveCategoryUpdateOne) Select(field string, fields ...string) *LiveCategoryUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated LiveCategory entity.
func (_u *LiveCategoryUpdateOne) Save(ctx context.Context) (*LiveCategory, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *LiveCategoryUpdateOne) SaveX(ctx context.Context) *LiveCategory {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *LiveCategoryUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *LiveCategoryUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *LiveCategoryUpdateOne) check() error {
	if _u.mutation.LiveCleared() && len(_u.mutation.LiveIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "LiveCategory.live"`)
	}
	return nil
}

func (_u *LiveCategoryUpdateOne) sqlSave(ctx context.Context) (_node *LiveCategory, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(livecategory.Table, livecategory.Columns, sqlgraph.NewFieldSpec(livecategory.FieldID, field.TypeUUID))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "LiveCategory.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, livecategory.FieldID)
		for _, f := range fields {
			if !livecategory.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != livecategory.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(livecategory.FieldName, field.TypeString, value)
	}
	if _u.mutation.NameCleared() {
		_spec.ClearField(livecategory.FieldName, field.TypeString)
	}
	if _u.mutation.LiveCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   livecategory.LiveTable,
			Columns: []string{livecategory.LiveColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(live.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.LiveIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   livecategory.LiveTable,
			Columns: []string{livecategory.LiveColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(live.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &LiveCategory{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{livecategory.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
