// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
	"github.com/zibbp/ganymede/ent/queue"
	"github.com/zibbp/ganymede/ent/vod"
	"github.com/zibbp/ganymede/internal/utils"
)

// QueueCreate is the builder for creating a Queue entity.
type QueueCreate struct {
	config
	mutation *QueueMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetLiveArchive sets the "live_archive" field.
func (_c *QueueCreate) SetLiveArchive(v bool) *QueueCreate {
	_c.mutation.SetLiveArchive(v)
	return _c
}

// SetNillableLiveArchive sets the "live_archive" field if the given value is not nil.
func (_c *QueueCreate) SetNillableLiveArchive(v *bool) *QueueCreate {
	if v != nil {
		_c.SetLiveArchive(*v)
	}
	return _c
}

// SetOnHold sets the "on_hold" field.
func (_c *QueueCreate) SetOnHold(v bool) *QueueCreate {
	_c.mutation.SetOnHold(v)
	return _c
}

// SetNillableOnHold sets the "on_hold" field if the given value is not nil.
func (_c *QueueCreate) SetNillableOnHold(v *bool) *QueueCreate {
	if v != nil {
		_c.SetOnHold(*v)
	}
	return _c
}

// SetVideoProcessing sets the "video_processing" field.
func (_c *QueueCreate) SetVideoProcessing(v bool) *QueueCreate {
	_c.mutation.SetVideoProcessing(v)
	return _c
}

// SetNillableVideoProcessing sets the "video_processing" field if the given value is not nil.
func (_c *QueueCreate) SetNillableVideoProcessing(v *bool) *QueueCreate {
	if v != nil {
		_c.SetVideoProcessing(*v)
	}
	return _c
}

// SetChatProcessing sets the "chat_processing" field.
func (_c *QueueCreate) SetChatProcessing(v bool) *QueueCreate {
	_c.mutation.SetChatProcessing(v)
	return _c
}

// SetNillableChatProcessing sets the "chat_processing" field if the given value is not nil.
func (_c *QueueCreate) SetNillableChatProcessing(v *bool) *QueueCreate {
	if v != nil {
		_c.SetChatProcessing(*v)
	}
	return _c
}

// SetProcessing sets the "processing" field.
func (_c *QueueCreate) SetProcessing(v bool) *QueueCreate {
	_c.mutation.SetProcessing(v)
	return _c
}

// SetNillableProcessing sets the "processing" field if the given value is not nil.
func (_c *QueueCreate) SetNillableProcessing(v *bool) *QueueCreate {
	if v != nil {
		_c.SetProcessing(*v)
	}
	return _c
}

// SetTaskVodCreateFolder sets the "task_vod_create_folder" field.
func (_c *QueueCreate) SetTaskVodCreateFolder(v utils.TaskStatus) *QueueCreate {
	_c.mutation.SetTaskVodCreateFolder(v)
	return _c
}

// SetNillableTaskVodCreateFolder sets the "task_vod_create_folder" field if the given value is not nil.
func (_c *QueueCreate) SetNillableTaskVodCreateFolder(v *utils.TaskStatus) *QueueCreate {
	if v != nil {
		_c.SetTaskVodCreateFolder(*v)
	}
	return _c
}

// SetTaskVodDownloadThumbnail sets the "task_vod_download_thumbnail" field.
func (_c *QueueCreate) SetTaskVodDownloadThumbnail(v utils.TaskStatus) *QueueCreate {
	_c.mutation.SetTaskVodDownloadThumbnail(v)
	return _c
}

// SetNillableTaskVodDownloadThumbnail sets the "task_vod_download_thumbnail" field if the given value is not nil.
func (_c *QueueCreate) SetNillableTaskVodDownloadThumbnail(v *utils.TaskStatus) *QueueCreate {
	if v != nil {
		_c.SetTaskVodDownloadThumbnail(*v)
	}
	return _c
}

// SetTaskVodSaveInfo sets the "task_vod_save_info" field.
func (_c *QueueCreate) SetTaskVodSaveInfo(v utils.TaskStatus) *QueueCreate {
	_c.mutation.SetTaskVodSaveInfo(v)
	return _c
}

// SetNillableTaskVodSaveInfo sets the "task_vod_save_info" field if the given value is not nil.
func (_c *QueueCreate) SetNillableTaskVodSaveInfo(v *utils.TaskStatus) *QueueCreate {
	if v != nil {
		_c.SetTaskVodSaveInfo(*v)
	}
	return _c
}

// SetTaskVideoDownload sets the "task_video_download" field.
func (_c *QueueCreate) SetTaskVideoDownload(v utils.TaskStatus) *QueueCreate {
	_c.mutation.SetTaskVideoDownload(v)
	return _c
}

// SetNillableTaskVideoDownload sets the "task_video_download" field if the given value is not nil.
func (_c *QueueCreate) SetNillableTaskVideoDownload(v *utils.TaskStatus) *QueueCreate {
	if v != nil {
		_c.SetTaskVideoDownload(*v)
	}
	return _c
}

// SetTaskVideoConvert sets the "task_video_convert" field.
func (_c *QueueCreate) SetTaskVideoConvert(v utils.TaskStatus) *QueueCreate {
	_c.mutation.SetTaskVideoConvert(v)
	return _c
}

// SetNillableTaskVideoConvert sets the "task_video_convert" field if the given value is not nil.
func (_c *QueueCreate) SetNillableTaskVideoConvert(v *utils.TaskStatus) *QueueCreate {
	if v != nil {
		_c.SetTaskVideoConvert(*v)
	}
	return _c
}

// SetTaskVideoMove sets the "task_video_move" field.
func (_c *QueueCreate) SetTaskVideoMove(v utils.TaskStatus) *QueueCreate {
	_c.mutation.SetTaskVideoMove(v)
	return _c
}

// SetNillableTaskVideoMove sets the "task_video_move" field if the given value is not nil.
func (_c *QueueCreate) SetNillableTaskVideoMove(v *utils.TaskStatus) *QueueCreate {
	if v != nil {
		_c.SetTaskVideoMove(*v)
	}
	return _c
}

// SetTaskChatDownload sets the "task_chat_download" field.
func (_c *QueueCreate) SetTaskChatDownload(v utils.TaskStatus) *QueueCreate {
	_c.mutation.SetTaskChatDownload(v)
	return _c
}

// SetNillableTaskChatDownload sets the "task_chat_download" field if the given value is not nil.
func (_c *QueueCreate) SetNillableTaskChatDownload(v *utils.TaskStatus) *QueueCreate {
	if v != nil {
		_c.SetTaskChatDownload(*v)
	}
	return _c
}

// SetTaskChatConvert sets the "task_chat_convert" field.
func (_c *QueueCreate) SetTaskChatConvert(v utils.TaskStatus) *QueueCreate {
	_c.mutation.SetTaskChatConvert(v)
	return _c
}

// SetNillableTaskChatConvert sets the "task_chat_convert" field if the given value is not nil.
func (_c *QueueCreate) SetNillableTaskChatConvert(v *utils.TaskStatus) *QueueCreate {
	if v != nil {
		_c.SetTaskChatConvert(*v)
	}
	return _c
}

// SetTaskChatRender sets the "task_chat_render" field.
func (_c *QueueCreate) SetTaskChatRender(v utils.TaskStatus) *QueueCreate {
	_c.mutation.SetTaskChatRender(v)
	return _c
}

// SetNillableTaskChatRender sets the "task_chat_render" field if the given value is not nil.
func (_c *QueueCreate) SetNillableTaskChatRender(v *utils.TaskStatus) *QueueCreate {
	if v != nil {
		_c.SetTaskChatRender(*v)
	}
	return _c
}

// SetTaskChatMove sets the "task_chat_move" field.
func (_c *QueueCreate) SetTaskChatMove(v utils.TaskStatus) *QueueCreate {
	_c.mutation.SetTaskChatMove(v)
	return _c
}

// SetNillableTaskChatMove sets the "task_chat_move" field if the given value is not nil.
func (_c *QueueCreate) SetNillableTaskChatMove(v *utils.TaskStatus) *QueueCreate {
	if v != nil {
		_c.SetTaskChatMove(*v)
	}
	return _c
}

// SetChatStart sets the "chat_start" field.
func (_c *QueueCreate) SetChatStart(v time.Time) *QueueCreate {
	_c.mutation.SetChatStart(v)
	return _c
}

// SetNillableChatStart sets the "chat_start" field if the given value is not nil.
func (_c *QueueCreate) SetNillableChatStart(v *time.Time) *QueueCreate {
	if v != nil {
		_c.SetChatStart(*v)
	}
	return _c
}

// SetArchiveChat sets the "archive_chat" field.
func (_c *QueueCreate) SetArchiveChat(v bool) *QueueCreate {
	_c.mutation.SetArchiveChat(v)
	return _c
}

// SetNillableArchiveChat sets the "archive_chat" field if the given value is not nil.
func (_c *QueueCreate) SetNillableArchiveChat(v *bool) *QueueCreate {
	if v != nil {
		_c.SetArchiveChat(*v)
	}
	return _c
}

// SetRenderChat sets the "render_chat" field.
func (_c *QueueCreate) SetRenderChat(v bool) *QueueCreate {
	_c.mutation.SetRenderChat(v)
	return _c
}

// SetNillableRenderChat sets the "render_chat" field if the given value is not nil.
func (_c *QueueCreate) SetNillableRenderChat(v *bool) *QueueCreate {
	if v != nil {
		_c.SetRenderChat(*v)
	}
	return _c
}

// SetWorkflowID sets the "workflow_id" field.
func (_c *QueueCreate) SetWorkflowID(v string) *QueueCreate {
	_c.mutation.SetWorkflowID(v)
	return _c
}

// SetNillableWorkflowID sets the "workflow_id" field if the given value is not nil.
func (_c *QueueCreate) SetNillableWorkflowID(v *string) *QueueCreate {
	if v != nil {
		_c.SetWorkflowID(*v)
	}
	return _c
}

// SetWorkflowRunID sets the "workflow_run_id" field.
func (_c *QueueCreate) SetWorkflowRunID(v string) *QueueCreate {
	_c.mutation.SetWorkflowRunID(v)
	return _c
}

// SetNillableWorkflowRunID sets the "workflow_run_id" field if the given value is not nil.
func (_c *QueueCreate) SetNillableWorkflowRunID(v *string) *QueueCreate {
	if v != nil {
		_c.SetWorkflowRunID(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *QueueCreate) SetUpdatedAt(v time.Time) *QueueCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *QueueCreate) SetNillableUpdatedAt(v *time.Time) *QueueCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *QueueCreate) SetCreatedAt(v time.Time) *QueueCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *QueueCreate) SetNillableCreatedAt(v *time.Time) *QueueCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetID sets the "id" field.
func (_c *QueueCreate) SetID(v uuid.UUID) *QueueCreate {
	_c.mutation.SetID(v)
	return _c
}

// SetNillableID sets the "id" field if the given value is not nil.
func (_c *QueueCreate) SetNillableID(v *uuid.UUID) *QueueCreate {
	if v != nil {
		_c.SetID(*v)
	}
	return _c
}

// SetVodID sets the "vod" edge to the Vod entity by ID.
func (_c *QueueCreate) SetVodID(id uuid.UUID) *QueueCreate {
	_c.mutation.SetVodID(id)
	return _c
}

// SetVod sets the "vod" edge to the Vod entity.
func (_c *QueueCreate) SetVod(v *Vod) *QueueCreate {
	return _c.SetVodID(v.ID)
}

// Mutation returns the QueueMutation object of the builder.
func (_c *QueueCreate) Mutation() *QueueMutation {
	return _c.mutation
}

// Save creates the Queue in the database.
func (_c *QueueCreate) Save(ctx context.Context) (*Queue, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *QueueCreate) SaveX(ctx context.Context) *Queue {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *QueueCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *QueueCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *QueueCreate) defaults() {
	if _, ok := _c.mutation.LiveArchive(); !ok {
		v := queue.DefaultLiveArchive
		_c.mutation.SetLiveArchive(v)
	}
	if _, ok := _c.mutation.OnHold(); !ok {
		v := queue.DefaultOnHold
		_c.mutation.SetOnHold(v)
	}
	if _, ok := _c.mutation.VideoProcessing(); !ok {
		v := queue.DefaultVideoProcessing
		_c.mutation.SetVideoProcessing(v)
	}
	if _, ok := _c.mutation.ChatProcessing(); !ok {
		v := queue.DefaultChatProcessing
		_c.mutation.SetChatProcessing(v)
	}
	if _, ok := _c.mutation.Processing(); !ok {
		v := queue.DefaultProcessing
		_c.mutation.SetProcessing(v)
	}
	if _, ok := _c.mutation.TaskVodCreateFolder(); !ok {
		v := queue.DefaultTaskVodCreateFolder
		_c.mutation.SetTaskVodCreateFolder(v)
	}
	if _, ok := _c.mutation.TaskVodDownloadThumbnail(); !ok {
		v := queue.DefaultTaskVodDownloadThumbnail
		_c.mutation.SetTaskVodDownloadThumbnail(v)
	}
	if _, ok := _c.mutation.TaskVodSaveInfo(); !ok {
		v := queue.DefaultTaskVodSaveInfo
		_c.mutation.SetTaskVodSaveInfo(v)
	}
	if _, ok := _c.mutation.TaskVideoDownload(); !ok {
		v := queue.DefaultTaskVideoDownload
		_c.mutation.SetTaskVideoDownload(v)
	}
	if _, ok := _c.mutation.TaskVideoConvert(); !ok {
		v := queue.DefaultTaskVideoConvert
		_c.mutation.SetTaskVideoConvert(v)
	}
	if _, ok := _c.mutation.TaskVideoMove(); !ok {
		v := queue.DefaultTaskVideoMove
		_c.mutation.SetTaskVideoMove(v)
	}
	if _, ok := _c.mutation.TaskChatDownload(); !ok {
		v := queue.DefaultTaskChatDownload
		_c.mutation.SetTaskChatDownload(v)
	}
	if _, ok := _c.mutation.TaskChatConvert(); !ok {
		v := queue.DefaultTaskChatConvert
		_c.mutation.SetTaskChatConvert(v)
	}
	if _, ok := _c.mutation.TaskChatRender(); !ok {
		v := queue.DefaultTaskChatRender
		_c.mutation.SetTaskChatRender(v)
	}
	if _, ok := _c.mutation.TaskChatMove(); !ok {
		v := queue.DefaultTaskChatMove
		_c.mutation.SetTaskChatMove(v)
	}
	if _, ok := _c.mutation.ArchiveChat(); !ok {
		v := queue.DefaultArchiveChat
		_c.mutation.SetArchiveChat(v)
	}
	if _, ok := _c.mutation.RenderChat(); !ok {
		v := queue.DefaultRenderChat
		_c.mutation.SetRenderChat(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := queue.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := queue.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.ID(); !ok {
		v := queue.DefaultID()
		_c.mutation.SetID(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *QueueCreate) check() error {
	if _, ok := _c.mutation.LiveArchive(); !ok {
		return &ValidationError{Name: "live_archive", err: errors.New(`ent: missing required field "Queue.live_archive"`)}
	}
	if _, ok := _c.mutation.OnHold(); !ok {
		return &ValidationError{Name: "on_hold", err: errors.New(`ent: missing required field "Queue.on_hold"`)}
	}
	if _, ok := _c.mutation.VideoProcessing(); !ok {
		return &ValidationError{Name: "video_processing", err: errors.New(`ent: missing required field "Queue.video_processing"`)}
	}
	if _, ok := _c.mutation.ChatProcessing(); !ok {
		return &ValidationError{Name: "chat_processing", err: errors.New(`ent: missing required field "Queue.chat_processing"`)}
	}
	if _, ok := _c.mutation.Processing(); !ok {
		return &ValidationError{Name: "processing", err: errors.New(`ent: missing required field "Queue.processing"`)}
	}
	if v, ok := _c.mutation.TaskVodCreateFolder(); ok {
		if err := queue.TaskVodCreateFolderValidator(v); err != nil {
			return &ValidationError{Name: "task_vod_create_folder", err: fmt.Errorf(`ent: validator failed for field "Queue.task_vod_create_folder": %w`, err)}
		}
	}
	if v, ok := _c.mutation.TaskVodDownloadThumbnail(); ok {
		if err := queue.TaskVodDownloadThumbnailValidator(v); err != nil {
			return &ValidationError{Name: "task_vod_download_thumbnail", err: fmt.Errorf(`ent: validator failed for field "Queue.task_vod_download_thumbnail": %w`, err)}
		}
	}
	if v, ok := _c.mutation.TaskVodSaveInfo(); ok {
		if err := queue.TaskVodSaveInfoValidator(v); err != nil {
			return &ValidationError{Name: "task_vod_save_info", err: fmt.Errorf(`ent: validator failed for field "Queue.task_vod_save_info": %w`, err)}
		}
	}
	if v, ok := _c.mutation.TaskVideoDownload(); ok {
		if err := queue.TaskVideoDownloadValidator(v); err != nil {
			return &ValidationError{Name: "task_video_download", err: fmt.Errorf(`ent: validator failed for field "Queue.task_video_download": %w`, err)}
		}
	}
	if v, ok := _c.mutation.TaskVideoConvert(); ok {
		if err := queue.TaskVideoConvertValidator(v); err != nil {
			return &ValidationError{Name: "task_video_convert", err: fmt.Errorf(`ent: validator failed for field "Queue.task_video_convert": %w`, err)}
		}
	}
	if v, ok := _c.mutation.TaskVideoMove(); ok {
		if err := queue.TaskVideoMoveValidator(v); err != nil {
			return &ValidationError{Name: "task_video_move", err: fmt.Errorf(`ent: validator failed for field "Queue.task_video_move": %w`, err)}
		}
	}
	if v, ok := _c.mutation.TaskChatDownload(); ok {
		if err := queue.TaskChatDownloadValidator(v); err != nil {
			return &ValidationError{Name: "task_chat_download", err: fmt.Errorf(`ent: validator failed for field "Queue.task_chat_download": %w`, err)}
		}
	}
	if v, ok := _c.mutation.TaskChatConvert(); ok {
		if err := queue.TaskChatConvertValidator(v); err != nil {
			return &ValidationError{Name: "task_chat_convert", err: fmt.Errorf(`ent: validator failed for field "Queue.task_chat_convert": %w`, err)}
		}
	}
	if v, ok := _c.mutation.TaskChatRender(); ok {
		if err := queue.TaskChatRenderValidator(v); err != nil {
			return &ValidationError{Name: "task_chat_render", err: fmt.Errorf(`ent: validator failed for field "Queue.task_chat_render": %w`, err)}
		}
	}
	if v, ok := _c.mutation.TaskChatMove(); ok {
		if err := queue.TaskChatMoveValidator(v); err != nil {
			return &ValidationError{Name: "task_chat_move", err: fmt.Errorf(`ent: validator failed for field "Queue.task_chat_move": %w`, err)}
		}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "Queue.updated_at"`)}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "Queue.created_at"`)}
	}
	if len(_c.mutation.VodIDs()) == 0 {
		return &ValidationError{Name: "vod", err: errors.New(`ent: missing required edge "Queue.vod"`)}
	}
	return nil
}

func (_c *QueueCreate) sqlSave(ctx context.Context) (*Queue, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(*uuid.UUID); ok {
			_node.ID = *id
		} else if err := _node.ID.Scan(_spec.ID.Value); err != nil {
			return nil, err
		}
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *QueueCreate) createSpec() (*Queue, *sqlgraph.CreateSpec) {
	var (
		_node = &Queue{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(queue.Table, sqlgraph.NewFieldSpec(queue.FieldID, field.TypeUUID))
	)
	_spec.OnConflict = _c.conflict
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = &id
	}
	if value, ok := _c.mutation.LiveArchive(); ok {
		_spec.SetField(queue.FieldLiveArchive, field.TypeBool, value)
		_node.LiveArchive = value
	}
	if value, ok := _c.mutation.OnHold(); ok {
		_spec.SetField(queue.FieldOnHold, field.TypeBool, value)
		_node.OnHold = value
	}
	if value, ok := _c.mutation.VideoProcessing(); ok {
		_spec.SetField(queue.FieldVideoProcessing, field.TypeBool, value)
		_node.VideoProcessing = value
	}
	if value, ok := _c.mutation.ChatProcessing(); ok {
		_spec.SetField(queue.FieldChatProcessing, field.TypeBool, value)
		_node.ChatProcessing = value
	}
	if value, ok := _c.mutation.Processing(); ok {
		_spec.SetField(queue.FieldProcessing, field.TypeBool, value)
		_node.Processing = value
	}
	if value, ok := _c.mutation.TaskVodCreateFolder(); ok {
		_spec.SetField(queue.FieldTaskVodCreateFolder, field.TypeEnum, value)
		_node.TaskVodCreateFolder = value
	}
	if value, ok := _c.mutation.TaskVodDownloadThumbnail(); ok {
		_spec.SetField(queue.FieldTaskVodDownloadThumbnail, field.TypeEnum, value)
		_node.TaskVodDownloadThumbnail = value
	}
	if value, ok := _c.mutation.TaskVodSaveInfo(); ok {
		_spec.SetField(queue.FieldTaskVodSaveInfo, field.TypeEnum, value)
		_node.TaskVodSaveInfo = value
	}
	if value, ok := _c.mutation.TaskVideoDownload(); ok {
		_spec.SetField(queue.FieldTaskVideoDownload, field.TypeEnum, value)
		_node.TaskVideoDownload = value
	}
	if value, ok := _c.mutation.TaskVideoConvert(); ok {
		_spec.SetField(queue.FieldTaskVideoConvert, field.TypeEnum, value)
		_node.TaskVideoConvert = value
	}
	if value, ok := _c.mutation.TaskVideoMove(); ok {
		_spec.SetField(queue.FieldTaskVideoMove, field.TypeEnum, value)
		_node.TaskVideoMove = value
	}
	if value, ok := _c.mutation.TaskChatDownload(); ok {
		_spec.SetField(queue.FieldTaskChatDownload, field.TypeEnum, value)
		_node.TaskChatDownload = value
	}
	if value, ok := _c.mutation.TaskChatConvert(); ok {
		_spec.SetField(queue.FieldTaskChatConvert, field.TypeEnum, value)
		_node.TaskChatConvert = value
	}
	if value, ok := _c.mutation.TaskChatRender(); ok {
		_spec.SetField(queue.FieldTaskChatRender, field.TypeEnum, value)
		_node.TaskChatRender = value
	}
	if value, ok := _c.mutation.TaskChatMove(); ok {
		_spec.SetField(queue.FieldTaskChatMove, field.TypeEnum, value)
		_node.TaskChatMove = value
	}
	if value, ok := _c.mutation.ChatStart(); ok {
		_spec.SetField(queue.FieldChatStart, field.TypeTime, value)
		_node.ChatStart = value
	}
	if value, ok := _c.mutation.ArchiveChat(); ok {
		_spec.SetField(queue.FieldArchiveChat, field.TypeBool, value)
		_node.ArchiveChat = value
	}
	if value, ok := _c.mutation.RenderChat(); ok {
		_spec.SetField(queue.FieldRenderChat, field.TypeBool, value)
		_node.RenderChat = value
	}
	if value, ok := _c.mutation.WorkflowID(); ok {
		_spec.SetField(queue.FieldWorkflowID, field.TypeString, value)
		_node.WorkflowID = value
	}
	if value, ok := _c.mutation.WorkflowRunID(); ok {
		_spec.SetField(queue.FieldWorkflowRunID, field.TypeString, value)
		_node.WorkflowRunID = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(queue.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(queue.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if nodes := _c.mutation.VodIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: true,
			Table:   queue.VodTable,
			Columns: []string{queue.VodColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(vod.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.vod_queue = &nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.Queue.Create().
//		SetLiveArchive(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.QueueUpsert) {
//			SetLiveArchive(v+v).
//		}).
//		Exec(ctx)
func (_c *QueueCreate) OnConflict(opts ...sql.ConflictOption) *QueueUpsertOne {
	_c.conflict = opts
	return &QueueUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.Queue.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *QueueCreate) OnConflictColumns(columns ...string) *QueueUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &QueueUpsertOne{
		create: _c,
	}
}

type (
	// QueueUpsertOne is the builder for "upsert"-ing
	//  one Queue node.
	QueueUpsertOne struct {
		create *QueueCreate
	}

	// QueueUpsert is the "OnConflict" setter.
	QueueUpsert struct {
		*sql.UpdateSet
	}
)

// SetLiveArchive sets the "live_archive" field.
func (u *QueueUpsert) SetLiveArchive(v bool) *QueueUpsert {
	u.Set(queue.FieldLiveArchive, v)
	return u
}

// UpdateLiveArchive sets the "live_archive" field to the value that was provided on create.
func (u *QueueUpsert) UpdateLiveArchive() *QueueUpsert {
	u.SetExcluded(queue.FieldLiveArchive)
	return u
}

// SetOnHold sets the "on_hold" field.
func (u *QueueUpsert) SetOnHold(v bool) *QueueUpsert {
	u.Set(queue.FieldOnHold, v)
	return u
}

// UpdateOnHold sets the "on_hold" field to the value that was provided on create.
func (u *QueueUpsert) UpdateOnHold() *QueueUpsert {
	u.SetExcluded(queue.FieldOnHold)
	return u
}

// SetVideoProcessing sets the "video_processing" field.
func (u *QueueUpsert) SetVideoProcessing(v bool) *QueueUpsert {
	u.Set(queue.FieldVideoProcessing, v)
	return u
}

// UpdateVideoProcessing sets the "video_processing" field to the value that was provided on create.
func (u *QueueUpsert) UpdateVideoProcessing() *QueueUpsert {
	u.SetExcluded(queue.FieldVideoProcessing)
	return u
}

// SetChatProcessing sets the "chat_processing" field.
func (u *QueueUpsert) SetChatProcessing(v bool) *QueueUpsert {
	u.Set(queue.FieldChatProcessing, v)
	return u
}

// UpdateChatProcessing sets the "chat_processing" field to the value that was provided on create.
func (u *QueueUpsert) UpdateChatProcessing() *QueueUpsert {
	u.SetExcluded(queue.FieldChatProcessing)
	return u
}

// SetProcessing sets the "processing" field.
func (u *QueueUpsert) SetProcessing(v bool) *QueueUpsert {
	u.Set(queue.FieldProcessing, v)
	return u
}

// UpdateProcessing sets the "processing" field to the value that was provided on create.
func (u *QueueUpsert) UpdateProcessing() *QueueUpsert {
	u.SetExcluded(queue.FieldProcessing)
	return u
}

// SetTaskVodCreateFolder sets the "task_vod_create_folder" field.
func (u *QueueUpsert) SetTaskVodCreateFolder(v utils.TaskStatus) *QueueUpsert {
	u.Set(queue.FieldTaskVodCreateFolder, v)
	return u
}

// UpdateTaskVodCreateFolder sets the "task_vod_create_folder" field to the value that was provided on create.
func (u *QueueUpsert) UpdateTaskVodCreateFolder() *QueueUpsert {
	u.SetExcluded(queue.FieldTaskVodCreateFolder)
	return u
}

// ClearTaskVodCreateFolder clears the value of the "task_vod_create_folder" field.
func (u *QueueUpsert) ClearTaskVodCreateFolder() *QueueUpsert {
	u.SetNull(queue.FieldTaskVodCreateFolder)
	return u
}

// SetTaskVodDownloadThumbnail sets the "task_vod_download_thumbnail" field.
func (u *QueueUpsert) SetTaskVodDownloadThumbnail(v utils.TaskStatus) *QueueUpsert {
	u.Set(queue.FieldTaskVodDownloadThumbnail, v)
	return u
}

// UpdateTaskVodDownloadThumbnail sets the "task_vod_download_thumbnail" field to the value that was provided on create.
func (u *QueueUpsert) UpdateTaskVodDownloadThumbnail() *QueueUpsert {
	u.SetExcluded(queue.FieldTaskVodDownloadThumbnail)
	return u
}

// ClearTaskVodDownloadThumbnail clears the value of the "task_vod_download_thumbnail" field.
func (u *QueueUpsert) ClearTaskVodDownloadThumbnail() *QueueUpsert {
	u.SetNull(queue.FieldTaskVodDownloadThumbnail)
	return u
}

// SetTaskVodSaveInfo sets the "task_vod_save_info" field.
func (u *QueueUpsert) SetTaskVodSaveInfo(v utils.TaskStatus) *QueueUpsert {
	u.Set(queue.FieldTaskVodSaveInfo, v)
	return u
}

// UpdateTaskVodSaveInfo sets the "task_vod_save_info" field to the value that was provided on create.
func (u *QueueUpsert) UpdateTaskVodSaveInfo() *QueueUpsert {
	u.SetExcluded(queue.FieldTaskVodSaveInfo)
	return u
}

// ClearTaskVodSaveInfo clears the value of the "task_vod_save_info" field.
func (u *QueueUpsert) ClearTaskVodSaveInfo() *QueueUpsert {
	u.SetNull(queue.FieldTaskVodSaveInfo)
	return u
}

// SetTaskVideoDownload sets the "task_video_download" field.
func (u *QueueUpsert) SetTaskVideoDownload(v utils.TaskStatus) *QueueUpsert {
	u.Set(queue.FieldTaskVideoDownload, v)
	return u
}

// UpdateTaskVideoDownload sets the "task_video_download" field to the value that was provided on create.
func (u *QueueUpsert) UpdateTaskVideoDownload() *QueueUpsert {
	u.SetExcluded(queue.FieldTaskVideoDownload)
	return u
}

// ClearTaskVideoDownload clears the value of the "task_video_download" field.
func (u *QueueUpsert) ClearTaskVideoDownload() *QueueUpsert {
	u.SetNull(queue.FieldTaskVideoDownload)
	return u
}

// SetTaskVideoConvert sets the "task_video_convert" field.
func (u *QueueUpsert) SetTaskVideoConvert(v utils.TaskStatus) *QueueUpsert {
	u.Set(queue.FieldTaskVideoConvert, v)
	return u
}

// UpdateTaskVideoConvert sets the "task_video_convert" field to the value that was provided on create.
func (u *QueueUpsert) UpdateTaskVideoConvert() *QueueUpsert {
	u.SetExcluded(queue.FieldTaskVideoConvert)
	return u
}

// ClearTaskVideoConvert clears the value of the "task_video_convert" field.
func (u *QueueUpsert) ClearTaskVideoConvert() *QueueUpsert {
	u.SetNull(queue.FieldTaskVideoConvert)
	return u
}

// SetTaskVideoMove sets the "task_video_move" field.
func (u *QueueUpsert) SetTaskVideoMove(v utils.TaskStatus) *QueueUpsert {
	u.Set(queue.FieldTaskVideoMove, v)
	return u
}

// UpdateTaskVideoMove sets the "task_video_move" field to the value that was provided on create.
func (u *QueueUpsert) UpdateTaskVideoMove() *QueueUpsert {
	u.SetExcluded(queue.FieldTaskVideoMove)
	return u
}

// ClearTaskVideoMove clears the value of the "task_video_move" field.
func (u *QueueUpsert) ClearTaskVideoMove() *QueueUpsert {
	u.SetNull(queue.FieldTaskVideoMove)
	return u
}

// SetTaskChatDownload sets the "task_chat_download" field.
func (u *QueueUpsert) SetTaskChatDownload(v utils.TaskStatus) *QueueUpsert {
	u.Set(queue.FieldTaskChatDownload, v)
	return u
}

// UpdateTaskChatDownload sets the "task_chat_download" field to the value that was provided on create.
func (u *QueueUpsert) UpdateTaskChatDownload() *QueueUpsert {
	u.SetExcluded(queue.FieldTaskChatDownload)
	return u
}

// ClearTaskChatDownload clears the value of the "task_chat_download" field.
func (u *QueueUpsert) ClearTaskChatDownload() *QueueUpsert {
	u.SetNull(queue.FieldTaskChatDownload)
	return u
}

// SetTaskChatConvert sets the "task_chat_convert" field.
func (u *QueueUpsert) SetTaskChatConvert(v utils.TaskStatus) *QueueUpsert {
	u.Set(queue.FieldTaskChatConvert, v)
	return u
}

// UpdateTaskChatConvert sets the "task_chat_convert" field to the value that was provided on create.
func (u *QueueUpsert) UpdateTaskChatConvert() *QueueUpsert {
	u.SetExcluded(queue.FieldTaskChatConvert)
	return u
}

// ClearTaskChatConvert clears the value of the "task_chat_convert" field.
func (u *QueueUpsert) ClearTaskChatConvert() *QueueUpsert {
	u.SetNull(queue.FieldTaskChatConvert)
	return u
}

// SetTaskChatRender sets the "task_chat_render" field.
func (u *QueueUpsert) SetTaskChatRender(v utils.TaskStatus) *QueueUpsert {
	u.Set(queue.FieldTaskChatRender, v)
	return u
}

// UpdateTaskChatRender sets the "task_chat_render" field to the value that was provided on create.
func (u *QueueUpsert) UpdateTaskChatRender() *QueueUpsert {
	u.SetExcluded(queue.FieldTaskChatRender)
	return u
}

// ClearTaskChatRender clears the value of the "task_chat_render" field.
func (u *QueueUpsert) ClearTaskChatRender() *QueueUpsert {
	u.SetNull(queue.FieldTaskChatRender)
	return u
}

// SetTaskChatMove sets the "task_chat_move" field.
func (u *QueueUpsert) SetTaskChatMove(v utils.TaskStatus) *QueueUpsert {
	u.Set(queue.FieldTaskChatMove, v)
	return u
}

// UpdateTaskChatMove sets the "task_chat_move" field to the value that was provided on create.
func (u *QueueUpsert) UpdateTaskChatMove() *QueueUpsert {
	u.SetExcluded(queue.FieldTaskChatMove)
	return u
}

// ClearTaskChatMove clears the value of the "task_chat_move" field.
func (u *QueueUpsert) ClearTaskChatMove() *QueueUpsert {
	u.SetNull(queue.FieldTaskChatMove)
	return u
}

// SetChatStart sets the "chat_start" field.
func (u *QueueUpsert) SetChatStart(v time.Time) *QueueUpsert {
	u.Set(queue.FieldChatStart, v)
	return u
}

// UpdateChatStart sets the "chat_start" field to the value that was provided on create.
func (u *QueueUpsert) UpdateChatStart() *QueueUpsert {
	u.SetExcluded(queue.FieldChatStart)
	return u
}

// ClearChatStart clears the value of the "chat_start" field.
func (u *QueueUpsert) ClearChatStart() *QueueUpsert {
	u.SetNull(queue.FieldChatStart)
	return u
}

// SetArchiveChat sets the "archive_chat" field.
func (u *QueueUpsert) SetArchiveChat(v bool) *QueueUpsert {
	u.Set(queue.FieldArchiveChat, v)
	return u
}

// UpdateArchiveChat sets the "archive_chat" field to the value that was provided on create.
func (u *QueueUpsert) UpdateArchiveChat() *QueueUpsert {
	u.SetExcluded(queue.FieldArchiveChat)
	return u
}

// ClearArchiveChat clears the value of the "archive_chat" field.
func (u *QueueUpsert) ClearArchiveChat() *QueueUpsert {
	u.SetNull(queue.FieldArchiveChat)
	return u
}

// SetRenderChat sets the "render_chat" field.
func (u *QueueUpsert) SetRenderChat(v bool) *QueueUpsert {
	u.Set(queue.FieldRenderChat, v)
	return u
}

// UpdateRenderChat sets the "render_chat" field to the value that was provided on create.
func (u *QueueUpsert) UpdateRenderChat() *QueueUpsert {
	u.SetExcluded(queue.FieldRenderChat)
	return u
}

// ClearRenderChat clears the value of the "render_chat" field.
func (u *QueueUpsert) ClearRenderChat() *QueueUpsert {
	u.SetNull(queue.FieldRenderChat)
	return u
}

// SetWorkflowID sets the "workflow_id" field.
func (u *QueueUpsert) SetWorkflowID(v string) *QueueUpsert {
	u.Set(queue.FieldWorkflowID, v)
	return u
}

// UpdateWorkflowID sets the "workflow_id" field to the value that was provided on create.
func (u *QueueUpsert) UpdateWorkflowID() *QueueUpsert {
	u.SetExcluded(queue.FieldWorkflowID)
	return u
}

// ClearWorkflowID clears the value of the "workflow_id" field.
func (u *QueueUpsert) ClearWorkflowID() *QueueUpsert {
	u.SetNull(queue.FieldWorkflowID)
	return u
}

// SetWorkflowRunID sets the "workflow_run_id" field.
func (u *QueueUpsert) SetWorkflowRunID(v string) *QueueUpsert {
	u.Set(queue.FieldWorkflowRunID, v)
	return u
}

// UpdateWorkflowRunID sets the "workflow_run_id" field to the value that was provided on create.
func (u *QueueUpsert) UpdateWorkflowRunID() *QueueUpsert {
	u.SetExcluded(queue.FieldWorkflowRunID)
	return u
}

// ClearWorkflowRunID clears the value of the "workflow_run_id" field.
func (u *QueueUpsert) ClearWorkflowRunID() *QueueUpsert {
	u.SetNull(queue.FieldWorkflowRunID)
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *QueueUpsert) SetUpdatedAt(v time.Time) *QueueUpsert {
	u.Set(queue.FieldUpdatedAt, v)
	return u
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *QueueUpsert) UpdateUpdatedAt() *QueueUpsert {
	u.SetExcluded(queue.FieldUpdatedAt)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create except the ID field.
// Using this option is equivalent to using:
//
//	client.Queue.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(queue.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *QueueUpsertOne) UpdateNewValues() *QueueUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.ID(); exists {
			s.SetIgnore(queue.FieldID)
		}
		if _, exists := u.create.mutation.CreatedAt(); exists {
			s.SetIgnore(queue.FieldCreatedAt)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.Queue.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *QueueUpsertOne) Ignore() *QueueUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *QueueUpsertOne) DoNothing() *QueueUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the QueueCreate.OnConflict
// documentation for more info.
func (u *QueueUpsertOne) Update(set func(*QueueUpsert)) *QueueUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&QueueUpsert{UpdateSet: update})
	}))
	return u
}

// SetLiveArchive sets the "live_archive" field.
func (u *QueueUpsertOne) SetLiveArchive(v bool) *QueueUpsertOne {
	return u.Update(func(s *QueueUpsert) {
		s.SetLiveArchive(v)
	})
}

// UpdateLiveArchive sets the "live_archive" field to the value that was provided on create.
func (u *QueueUpsertOne) UpdateLiveArchive() *QueueUpsertOne {
	return u.Update(func(s *QueueUpsert) {
		s.UpdateLiveArchive()
	})
}

// SetOnHold sets the "on_hold" field.
func (u *QueueUpsertOne) SetOnHold(v bool) *QueueUpsertOne {
	return u.Update(func(s *QueueUpsert) {
		s.SetOnHold(v)
	})
}

// UpdateOnHold sets the "on_hold" field to the value that was provided on create.
func (u *QueueUpsertOne) UpdateOnHold() *QueueUpsertOne {
	return u.Update(func(s *QueueUpsert) {
		s.UpdateOnHold()
	})
}

// SetVideoProcessing sets the "video_processing" field.
func (u *QueueUpsertOne) SetVideoProcessing(v bool) *QueueUpsertOne {
	return u.Update(func(s *QueueUpsert) {
		s.SetVideoProcessing(v)
	})
}

// UpdateVideoProcessing sets the "video_processing" field to the value that was provided on create.
func (u *QueueUpsertOne) UpdateVideoProcessing() *QueueUpsertOne {
	return u.Update(func(s *QueueUpsert) {
		s.UpdateVideoProcessing()
	})
}

// SetChatProcessing sets the "chat_processing" field.
func (u *QueueUpsertOne) SetChatProcessing(v bool) *QueueUpsertOne {
	return u.Update(func(s *QueueUpsert) {
		s.SetChatProcessing(v)
	})
}

// UpdateChatProcessing sets the "chat_processing" field to the value that was provided on create.
func (u *QueueUpsertOne) UpdateChatProcessing() *QueueUpsertOne {
	return u.Update(func(s *QueueUpsert) {
		s.UpdateChatProcessing()
	})
}

// SetProcessing sets the "processing" field.
func (u *QueueUpsertOne) SetProcessing(v bool) *QueueUpsertOne {
	return u.Update(func(s *QueueUpsert) {
		s.SetProcessing(v)
	})
}

// UpdateProcessing sets the "processing" field to the value that was provided on create.
func (u *QueueUpsertOne) UpdateProcessing() *QueueUpsertOne {
	return u.Update(func(s *QueueUpsert) {
		s.UpdateProcessing()
	})
}

// SetTaskVodCreateFolder sets the "task_vod_create_folder" field.
func (u *QueueUpsertOne) SetTaskVodCreateFolder(v utils.TaskStatus) *QueueUpsertOne {
	return u.Update(func(s *QueueUpsert) {
		s.SetTaskVodCreateFolder(v)
	})
}

// UpdateTaskVodCreateFolder sets the "task_vod_create_folder" field to the value that was provided on create.
func (u *QueueUpsertOne) UpdateTaskVodCreateFolder() *QueueUpsertOne {
	return u.Update(func(s *QueueUpsert) {
		s.UpdateTaskVodCreateFolder()
	})
}

// ClearTaskVodCreateFolder clears the value of the "task_vod_create_folder" field.
func (u *QueueUpsertOne) ClearTaskVodCreateFolder() *QueueUpsertOne {
	return u.Update(func(s *QueueUpsert) {
		s.ClearTaskVodCreateFolder()
	})
}

// SetTaskVodDownloadThumbnail sets the "task_vod_download_thumbnail" field.
func (u *QueueUpsertOne) SetTaskVodDownloadThumbnail(v utils.TaskStatus) *QueueUpsertOne {
	return u.Update(func(s *QueueUpsert) {
		s.SetTaskVodDownloadThumbnail(v)
	})
}

// UpdateTaskVodDownloadThumbnail sets the "task_vod_download_thumbnail" field to the value that was provided on create.
func (u *QueueUpsertOne) UpdateTaskVodDownloadThumbnail() *QueueUpsertOne {
	return u.Update(func(s *QueueUpsert) {
		s.UpdateTaskVodDownloadThumbnail()
	})
}

// ClearTaskVodDownloadThumbnail clears the value of the "task_vod_download_thumbnail" field.
func (u *QueueUpsertOne) ClearTaskVodDownloadThumbnail() *QueueUpsertOne {
	return u.Update(func(s *QueueUpsert) {
		s.ClearTaskVodDownloadThumbnail()
	})
}

// SetTaskVodSaveInfo sets the "task_vod_save_info" field.
func (u *QueueUpsertOne) SetTaskVodSaveInfo(v utils.TaskStatus) *QueueUpsertOne {
	return u.Update(func(s *QueueUpsert) {
		s.SetTaskVodSaveInfo(v)
	})
}

// UpdateTaskVodSaveInfo sets the "task_vod_save_info" field to the value that was provided on create.
func (u *QueueUpsertOne) UpdateTaskVodSaveInfo() *QueueUpsertOne {
	return u.Update(func(s *QueueUpsert) {
		s.UpdateTaskVodSaveInfo()
	})
}

// ClearTaskVodSaveInfo clears the value of the "task_vod_save_info" field.
func (u *QueueUpsertOne) ClearTaskVodSaveInfo() *QueueUpsertOne {
	return u.Update(func(s *QueueUpsert) {
		s.ClearTaskVodSaveInfo()
	})
}

// SetTaskVideoDownload sets the "task_video_download" field.
func (u *QueueUpsertOne) SetTaskVideoDownload(v utils.TaskStatus) *QueueUpsertOne {
	return u.Update(func(s *QueueUpsert) {
		s.SetTaskVideoDownload(v)
	})
}

// UpdateTaskVideoDownload sets the "task_video_download" field to the value that was provided on create.
func (u *QueueUpsertOne) UpdateTaskVideoDownload() *QueueUpsertOne {
	return u.Update(func(s *QueueUpsert) {
		s.UpdateTaskVideoDownload()
	})
}

// ClearTaskVideoDownload clears the value of the "task_video_download" field.
func (u *QueueUpsertOne) ClearTaskVideoDownload() *QueueUpsertOne {
	return u.Update(func(s *QueueUpsert) {
		s.ClearTaskVideoDownload()
	})
}

// SetTaskVideoConvert sets the "task_video_convert" field.
func (u *QueueUpsertOne) SetTaskVideoConvert(v utils.TaskStatus) *QueueUpsertOne {
	return u.Update(func(s *QueueUpsert) {
		s.SetTaskVideoConvert(v)
	})
}

// UpdateTaskVideoConvert sets the "task_video_convert" field to the value that was provided on create.
func (u *QueueUpsertOne) UpdateTaskVideoConvert() *QueueUpsertOne {
	return u.Update(func(s *QueueUpsert) {
		s.UpdateTaskVideoConvert()
	})
}

// ClearTaskVideoConvert clears the value of the "task_video_convert" field.
func (u *QueueUpsertOne) ClearTaskVideoConvert() *QueueUpsertOne {
	return u.Update(func(s *QueueUpsert) {
		s.ClearTaskVideoConvert()
	})
}

// SetTaskVideoMove sets the "task_video_move" field.
func (u *QueueUpsertOne) SetTaskVideoMove(v utils.TaskStatus) *QueueUpsertOne {
	return u.Update(func(s *QueueUpsert) {
		s.SetTaskVideoMove(v)
	})
}

// UpdateTaskVideoMove sets the "task_video_move" field to the value that was provided on create.
func (u *QueueUpsertOne) UpdateTaskVideoMove() *QueueUpsertOne {
	return u.Update(func(s *QueueUpsert) {
		s.UpdateTaskVideoMove()
	})
}

// ClearTaskVideoMove clears the value of the "task_video_move" field.
func (u *QueueUpsertOne) ClearTaskVideoMove() *QueueUpsertOne {
	return u.Update(func(s *QueueUpsert) {
		s.ClearTaskVideoMove()
	})
}

// SetTaskChatDownload sets the "task_chat_download" field.
func (u *QueueUpsertOne) SetTaskChatDownload(v utils.TaskStatus) *QueueUpsertOne {
	return u.Update(func(s *QueueUpsert) {
		s.SetTaskChatDownload(v)
	})
}

// UpdateTaskChatDownload sets the "task_chat_download" field to the value that was provided on create.
func (u *QueueUpsertOne) UpdateTaskChatDownload() *QueueUpsertOne {
	return u.Update(func(s *QueueUpsert) {
		s.UpdateTaskChatDownload()
	})
}

// ClearTaskChatDownload clears the value of the "task_chat_download" field.
func (u *QueueUpsertOne) ClearTaskChatDownload() *QueueUpsertOne {
	return u.Update(func(s *QueueUpsert) {
		s.ClearTaskChatDownload()
	})
}

// SetTaskChatConvert sets the "task_chat_convert" field.
func (u *QueueUpsertOne) SetTaskChatConvert(v utils.TaskStatus) *QueueUpsertOne {
	return u.Update(func(s *QueueUpsert) {
		s.SetTaskChatConvert(v)
	})
}

// UpdateTaskChatConvert sets the "task_chat_convert" field to the value that was provided on create.
func (u *QueueUpsertOne) UpdateTaskChatConvert() *QueueUpsertOne {
	return u.Update(func(s *QueueUpsert) {
		s.UpdateTaskChatConvert()
	})
}

// ClearTaskChatConvert clears the value of the "task_chat_convert" field.
func (u *QueueUpsertOne) ClearTaskChatConvert() *QueueUpsertOne {
	return u.Update(func(s *QueueUpsert) {
		s.ClearTaskChatConvert()
	})
}

// SetTaskChatRender sets the "task_chat_render" field.
func (u *QueueUpsertOne) SetTaskChatRender(v utils.TaskStatus) *QueueUpsertOne {
	return u.Update(func(s *QueueUpsert) {
		s.SetTaskChatRender(v)
	})
}

// UpdateTaskChatRender sets the "task_chat_render" field to the value that was provided on create.
func (u *QueueUpsertOne) UpdateTaskChatRender() *QueueUpsertOne {
	return u.Update(func(s *QueueUpsert) {
		s.UpdateTaskChatRender()
	})
}

// ClearTaskChatRender clears the value of the "task_chat_render" field.
func (u *QueueUpsertOne) ClearTaskChatRender() *QueueUpsertOne {
	return u.Update(func(s *QueueUpsert) {
		s.ClearTaskChatRender()
	})
}

// SetTaskChatMove sets the "task_chat_move" field.
func (u *QueueUpsertOne) SetTaskChatMove(v utils.TaskStatus) *QueueUpsertOne {
	return u.Update(func(s *QueueUpsert) {
		s.SetTaskChatMove(v)
	})
}

// UpdateTaskChatMove sets the "task_chat_move" field to the value that was provided on create.
func (u *QueueUpsertOne) UpdateTaskChatMove() *QueueUpsertOne {
	return u.Update(func(s *QueueUpsert) {
		s.UpdateTaskChatMove()
	})
}

// ClearTaskChatMove clears the value of the "task_chat_move" field.
func (u *QueueUpsertOne) ClearTaskChatMove() *QueueUpsertOne {
	return u.Update(func(s *QueueUpsert) {
		s.ClearTaskChatMove()
	})
}

// SetChatStart sets the "chat_start" field.
func (u *QueueUpsertOne) SetChatStart(v time.Time) *QueueUpsertOne {
	return u.Update(func(s *QueueUpsert) {
		s.SetChatStart(v)
	})
}

// UpdateChatStart sets the "chat_start" field to the value that was provided on create.
func (u *QueueUpsertOne) UpdateChatStart() *QueueUpsertOne {
	return u.Update(func(s *QueueUpsert) {
		s.UpdateChatStart()
	})
}

// ClearChatStart clears the value of the "chat_start" field.
func (u *QueueUpsertOne) ClearChatStart() *QueueUpsertOne {
	return u.Update(func(s *QueueUpsert) {
		s.ClearChatStart()
	})
}

// SetArchiveChat sets the "archive_chat" field.
func (u *QueueUpsertOne) SetArchiveChat(v bool) *QueueUpsertOne {
	return u.Update(func(s *QueueUpsert) {
		s.SetArchiveChat(v)
	})
}

// UpdateArchiveChat sets the "archive_chat" field to the value that was provided on create.
func (u *QueueUpsertOne) UpdateArchiveChat() *QueueUpsertOne {
	return u.Update(func(s *QueueUpsert) {
		s.UpdateArchiveChat()
	})
}

// ClearArchiveChat clears the value of the "archive_chat" field.
func (u *QueueUpsertOne) ClearArchiveChat() *QueueUpsertOne {
	return u.Update(func(s *QueueUpsert) {
		s.ClearArchiveChat()
	})
}

// SetRenderChat sets the "render_chat" field.
func (u *QueueUpsertOne) SetRenderChat(v bool) *QueueUpsertOne {
	return u.Update(func(s *QueueUpsert) {
		s.SetRenderChat(v)
	})
}

// UpdateRenderChat sets the "render_chat" field to the value that was provided on create.
func (u *QueueUpsertOne) UpdateRenderChat() *QueueUpsertOne {
	return u.Update(func(s *QueueUpsert) {
		s.UpdateRenderChat()
	})
}

// ClearRenderChat clears the value of the "render_chat" field.
func (u *QueueUpsertOne) ClearRenderChat() *QueueUpsertOne {
	return u.Update(func(s *QueueUpsert) {
		s.ClearRenderChat()
	})
}

// SetWorkflowID sets the "workflow_id" field.
func (u *QueueUpsertOne) SetWorkflowID(v string) *QueueUpsertOne {
	return u.Update(func(s *QueueUpsert) {
		s.SetWorkflowID(v)
	})
}

// UpdateWorkflowID sets the "workflow_id" field to the value that was provided on create.
func (u *QueueUpsertOne) UpdateWorkflowID() *QueueUpsertOne {
	return u.Update(func(s *QueueUpsert) {
		s.UpdateWorkflowID()
	})
}

// ClearWorkflowID clears the value of the "workflow_id" field.
func (u *QueueUpsertOne) ClearWorkflowID() *QueueUpsertOne {
	return u.Update(func(s *QueueUpsert) {
		s.ClearWorkflowID()
	})
}

// SetWorkflowRunID sets the "workflow_run_id" field.
func (u *QueueUpsertOne) SetWorkflowRunID(v string) *QueueUpsertOne {
	return u.Update(func(s *QueueUpsert) {
		s.SetWorkflowRunID(v)
	})
}

// UpdateWorkflowRunID sets the "workflow_run_id" field to the value that was provided on create.
func (u *QueueUpsertOne) UpdateWorkflowRunID() *QueueUpsertOne {
	return u.Update(func(s *QueueUpsert) {
		s.UpdateWorkflowRunID()
	})
}

// ClearWorkflowRunID clears the value of the "workflow_run_id" field.
func (u *QueueUpsertOne) ClearWorkflowRunID() *QueueUpsertOne {
	return u.Update(func(s *QueueUpsert) {
		s.ClearWorkflowRunID()
	})
}

// SetUpdatedAt sets the "updated_at" field.
func (u *QueueUpsertOne) SetUpdatedAt(v time.Time) *QueueUpsertOne {
	return u.Update(func(s *QueueUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *QueueUpsertOne) UpdateUpdatedAt() *QueueUpsertOne {
	return u.Update(func(s *QueueUpsert) {
		s.UpdateUpdatedAt()
	})
}

// Exec executes the query.
func (u *QueueUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for QueueCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *QueueUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *QueueUpsertOne) ID(ctx context.Context) (id uuid.UUID, err error) {
	if u.create.driver.Dialect() == dialect.MySQL {
		// In case of "ON CONFLICT", there is no way to get back non-numeric ID
		// fields from the database since MySQL does not support the RETURNING clause.
		return id, errors.New("ent: QueueUpsertOne.ID is not supported by MySQL driver. Use QueueUpsertOne.Exec instead")
	}
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *QueueUpsertOne) IDX(ctx context.Context) uuid.UUID {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// QueueCreateBulk is the builder for creating many Queue entities in bulk.
type QueueCreateBulk struct {
	config
	err      error
	builders []*QueueCreate
	conflict []sql.ConflictOption
}

// Save creates the Queue entities in the database.
func (_c *QueueCreateBulk) Save(ctx context.Context) ([]*Queue, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*Queue, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*QueueMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *QueueCreateBulk) SaveX(ctx context.Context) []*Queue {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *QueueCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *QueueCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.Queue.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.QueueUpsert) {
//			SetLiveArchive(v+v).
//		}).
//		Exec(ctx)
func (_c *QueueCreateBulk) OnConflict(opts ...sql.ConflictOption) *QueueUpsertBulk {
	_c.conflict = opts
	return &QueueUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.Queue.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *QueueCreateBulk) OnConflictColumns(columns ...string) *QueueUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &QueueUpsertBulk{
		create: _c,
	}
}

// QueueUpsertBulk is the builder for "upsert"-ing
// a bulk of Queue nodes.
type QueueUpsertBulk struct {
	create *QueueCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.Queue.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(queue.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *QueueUpsertBulk) UpdateNewValues() *QueueUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.ID(); exists {
				s.SetIgnore(queue.FieldID)
			}
			if _, exists := b.mutation.CreatedAt(); exists {
				s.SetIgnore(queue.FieldCreatedAt)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.Queue.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *QueueUpsertBulk) Ignore() *QueueUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *QueueUpsertBulk) DoNothing() *QueueUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the QueueCreateBulk.OnConflict
// documentation for more info.
func (u *QueueUpsertBulk) Update(set func(*QueueUpsert)) *QueueUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&QueueUpsert{UpdateSet: update})
	}))
	return u
}

// SetLiveArchive sets the "live_archive" field.
func (u *QueueUpsertBulk) SetLiveArchive(v bool) *QueueUpsertBulk {
	return u.Update(func(s *QueueUpsert) {
		s.SetLiveArchive(v)
	})
}

// UpdateLiveArchive sets the "live_archive" field to the value that was provided on create.
func (u *QueueUpsertBulk) UpdateLiveArchive() *QueueUpsertBulk {
	return u.Update(func(s *QueueUpsert) {
		s.UpdateLiveArchive()
	})
}

// SetOnHold sets the "on_hold" field.
func (u *QueueUpsertBulk) SetOnHold(v bool) *QueueUpsertBulk {
	return u.Update(func(s *QueueUpsert) {
		s.SetOnHold(v)
	})
}

// UpdateOnHold sets the "on_hold" field to the value that was provided on create.
func (u *QueueUpsertBulk) UpdateOnHold() *QueueUpsertBulk {
	return u.Update(func(s *QueueUpsert) {
		s.UpdateOnHold()
	})
}

// SetVideoProcessing sets the "video_processing" field.
func (u *QueueUpsertBulk) SetVideoProcessing(v bool) *QueueUpsertBulk {
	return u.Update(func(s *QueueUpsert) {
		s.SetVideoProcessing(v)
	})
}

// UpdateVideoProcessing sets the "video_processing" field to the value that was provided on create.
func (u *QueueUpsertBulk) UpdateVideoProcessing() *QueueUpsertBulk {
	return u.Update(func(s *QueueUpsert) {
		s.UpdateVideoProcessing()
	})
}

// SetChatProcessing sets the "chat_processing" field.
func (u *QueueUpsertBulk) SetChatProcessing(v bool) *QueueUpsertBulk {
	return u.Update(func(s *QueueUpsert) {
		s.SetChatProcessing(v)
	})
}

// UpdateChatProcessing sets the "chat_processing" field to the value that was provided on create.
func (u *QueueUpsertBulk) UpdateChatProcessing() *QueueUpsertBulk {
	return u.Update(func(s *QueueUpsert) {
		s.UpdateChatProcessing()
	})
}

// SetProcessing sets the "processing" field.
func (u *QueueUpsertBulk) SetProcessing(v bool) *QueueUpsertBulk {
	return u.Update(func(s *QueueUpsert) {
		s.SetProcessing(v)
	})
}

// UpdateProcessing sets the "processing" field to the value that was provided on create.
func (u *QueueUpsertBulk) UpdateProcessing() *QueueUpsertBulk {
	return u.Update(func(s *QueueUpsert) {
		s.UpdateProcessing()
	})
}

// SetTaskVodCreateFolder sets the "task_vod_create_folder" field.
func (u *QueueUpsertBulk) SetTaskVodCreateFolder(v utils.TaskStatus) *QueueUpsertBulk {
	return u.Update(func(s *QueueUpsert) {
		s.SetTaskVodCreateFolder(v)
	})
}

// UpdateTaskVodCreateFolder sets the "task_vod_create_folder" field to the value that was provided on create.
func (u *QueueUpsertBulk) UpdateTaskVodCreateFolder() *QueueUpsertBulk {
	return u.Update(func(s *QueueUpsert) {
		s.UpdateTaskVodCreateFolder()
	})
}

// ClearTaskVodCreateFolder clears the value of the "task_vod_create_folder" field.
func (u *QueueUpsertBulk) ClearTaskVodCreateFolder() *QueueUpsertBulk {
	return u.Update(func(s *QueueUpsert) {
		s.ClearTaskVodCreateFolder()
	})
}

// SetTaskVodDownloadThumbnail sets the "task_vod_download_thumbnail" field.
func (u *QueueUpsertBulk) SetTaskVodDownloadThumbnail(v utils.TaskStatus) *QueueUpsertBulk {
	return u.Update(func(s *QueueUpsert) {
		s.SetTaskVodDownloadThumbnail(v)
	})
}

// UpdateTaskVodDownloadThumbnail sets the "task_vod_download_thumbnail" field to the value that was provided on create.
func (u *QueueUpsertBulk) UpdateTaskVodDownloadThumbnail() *QueueUpsertBulk {
	return u.Update(func(s *QueueUpsert) {
		s.UpdateTaskVodDownloadThumbnail()
	})
}

// ClearTaskVodDownloadThumbnail clears the value of the "task_vod_download_thumbnail" field.
func (u *QueueUpsertBulk) ClearTaskVodDownloadThumbnail() *QueueUpsertBulk {
	return u.Update(func(s *QueueUpsert) {
		s.ClearTaskVodDownloadThumbnail()
	})
}

// SetTaskVodSaveInfo sets the "task_vod_save_info" field.
func (u *QueueUpsertBulk) SetTaskVodSaveInfo(v utils.TaskStatus) *QueueUpsertBulk {
	return u.Update(func(s *QueueUpsert) {
		s.SetTaskVodSaveInfo(v)
	})
}

// UpdateTaskVodSaveInfo sets the "task_vod_save_info" field to the value that was provided on create.
func (u *QueueUpsertBulk) UpdateTaskVodSaveInfo() *QueueUpsertBulk {
	return u.Update(func(s *QueueUpsert) {
		s.UpdateTaskVodSaveInfo()
	})
}

// ClearTaskVodSaveInfo clears the value of the "task_vod_save_info" field.
func (u *QueueUpsertBulk) ClearTaskVodSaveInfo() *QueueUpsertBulk {
	return u.Update(func(s *QueueUpsert) {
		s.ClearTaskVodSaveInfo()
	})
}

// SetTaskVideoDownload sets the "task_video_download" field.
func (u *QueueUpsertBulk) SetTaskVideoDownload(v utils.TaskStatus) *QueueUpsertBulk {
	return u.Update(func(s *QueueUpsert) {
		s.SetTaskVideoDownload(v)
	})
}

// UpdateTaskVideoDownload sets the "task_video_download" field to the value that was provided on create.
func (u *QueueUpsertBulk) UpdateTaskVideoDownload() *QueueUpsertBulk {
	return u.Update(func(s *QueueUpsert) {
		s.UpdateTaskVideoDownload()
	})
}

// ClearTaskVideoDownload clears the value of the "task_video_download" field.
func (u *QueueUpsertBulk) ClearTaskVideoDownload() *QueueUpsertBulk {
	return u.Update(func(s *QueueUpsert) {
		s.ClearTaskVideoDownload()
	})
}

// SetTaskVideoConvert sets the "task_video_convert" field.
func (u *QueueUpsertBulk) SetTaskVideoConvert(v utils.TaskStatus) *QueueUpsertBulk {
	return u.Update(func(s *QueueUpsert) {
		s.SetTaskVideoConvert(v)
	})
}

// UpdateTaskVideoConvert sets the "task_video_convert" field to the value that was provided on create.
func (u *QueueUpsertBulk) UpdateTaskVideoConvert() *QueueUpsertBulk {
	return u.Update(func(s *QueueUpsert) {
		s.UpdateTaskVideoConvert()
	})
}

// ClearTaskVideoConvert clears the value of the "task_video_convert" field.
func (u *QueueUpsertBulk) ClearTaskVideoConvert() *QueueUpsertBulk {
	return u.Update(func(s *QueueUpsert) {
		s.ClearTaskVideoConvert()
	})
}

// SetTaskVideoMove sets the "task_video_move" field.
func (u *QueueUpsertBulk) SetTaskVideoMove(v utils.TaskStatus) *QueueUpsertBulk {
	return u.Update(func(s *QueueUpsert) {
		s.SetTaskVideoMove(v)
	})
}

// UpdateTaskVideoMove sets the "task_video_move" field to the value that was provided on create.
func (u *QueueUpsertBulk) UpdateTaskVideoMove() *QueueUpsertBulk {
	return u.Update(func(s *QueueUpsert) {
		s.UpdateTaskVideoMove()
	})
}

// ClearTaskVideoMove clears the value of the "task_video_move" field.
func (u *QueueUpsertBulk) ClearTaskVideoMove() *QueueUpsertBulk {
	return u.Update(func(s *QueueUpsert) {
		s.ClearTaskVideoMove()
	})
}

// SetTaskChatDownload sets the "task_chat_download" field.
func (u *QueueUpsertBulk) SetTaskChatDownload(v utils.TaskStatus) *QueueUpsertBulk {
	return u.Update(func(s *QueueUpsert) {
		s.SetTaskChatDownload(v)
	})
}

// UpdateTaskChatDownload sets the "task_chat_download" field to the value that was provided on create.
func (u *QueueUpsertBulk) UpdateTaskChatDownload() *QueueUpsertBulk {
	return u.Update(func(s *QueueUpsert) {
		s.UpdateTaskChatDownload()
	})
}

// ClearTaskChatDownload clears the value of the "task_chat_download" field.
func (u *QueueUpsertBulk) ClearTaskChatDownload() *QueueUpsertBulk {
	return u.Update(func(s *QueueUpsert) {
		s.ClearTaskChatDownload()
	})
}

// SetTaskChatConvert sets the "task_chat_convert" field.
func (u *QueueUpsertBulk) SetTaskChatConvert(v utils.TaskStatus) *QueueUpsertBulk {
	return u.Update(func(s *QueueUpsert) {
		s.SetTaskChatConvert(v)
	})
}

// UpdateTaskChatConvert sets the "task_chat_convert" field to the value that was provided on create.
func (u *QueueUpsertBulk) UpdateTaskChatConvert() *QueueUpsertBulk {
	return u.Update(func(s *QueueUpsert) {
		s.UpdateTaskChatConvert()
	})
}

// ClearTaskChatConvert clears the value of the "task_chat_convert" field.
func (u *QueueUpsertBulk) ClearTaskChatConvert() *QueueUpsertBulk {
	return u.Update(func(s *QueueUpsert) {
		s.ClearTaskChatConvert()
	})
}

// SetTaskChatRender sets the "task_chat_render" field.
func (u *QueueUpsertBulk) SetTaskChatRender(v utils.TaskStatus) *QueueUpsertBulk {
	return u.Update(func(s *QueueUpsert) {
		s.SetTaskChatRender(v)
	})
}

// UpdateTaskChatRender sets the "task_chat_render" field to the value that was provided on create.
func (u *QueueUpsertBulk) UpdateTaskChatRender() *QueueUpsertBulk {
	return u.Update(func(s *QueueUpsert) {
		s.UpdateTaskChatRender()
	})
}

// ClearTaskChatRender clears the value of the "task_chat_render" field.
func (u *QueueUpsertBulk) ClearTaskChatRender() *QueueUpsertBulk {
	return u.Update(func(s *QueueUpsert) {
		s.ClearTaskChatRender()
	})
}

// SetTaskChatMove sets the "task_chat_move" field.
func (u *QueueUpsertBulk) SetTaskChatMove(v utils.TaskStatus) *QueueUpsertBulk {
	return u.Update(func(s *QueueUpsert) {
		s.SetTaskChatMove(v)
	})
}

// UpdateTaskChatMove sets the "task_chat_move" field to the value that was provided on create.
func (u *QueueUpsertBulk) UpdateTaskChatMove() *QueueUpsertBulk {
	return u.Update(func(s *QueueUpsert) {
		s.UpdateTaskChatMove()
	})
}

// ClearTaskChatMove clears the value of the "task_chat_move" field.
func (u *QueueUpsertBulk) ClearTaskChatMove() *QueueUpsertBulk {
	return u.Update(func(s *QueueUpsert) {
		s.ClearTaskChatMove()
	})
}

// SetChatStart sets the "chat_start" field.
func (u *QueueUpsertBulk) SetChatStart(v time.Time) *QueueUpsertBulk {
	return u.Update(func(s *QueueUpsert) {
		s.SetChatStart(v)
	})
}

// UpdateChatStart sets the "chat_start" field to the value that was provided on create.
func (u *QueueUpsertBulk) UpdateChatStart() *QueueUpsertBulk {
	return u.Update(func(s *QueueUpsert) {
		s.UpdateChatStart()
	})
}

// ClearChatStart clears the value of the "chat_start" field.
func (u *QueueUpsertBulk) ClearChatStart() *QueueUpsertBulk {
	return u.Update(func(s *QueueUpsert) {
		s.ClearChatStart()
	})
}

// SetArchiveChat sets the "archive_chat" field.
func (u *QueueUpsertBulk) SetArchiveChat(v bool) *QueueUpsertBulk {
	return u.Update(func(s *QueueUpsert) {
		s.SetArchiveChat(v)
	})
}

// UpdateArchiveChat sets the "archive_chat" field to the value that was provided on create.
func (u *QueueUpsertBulk) UpdateArchiveChat() *QueueUpsertBulk {
	return u.Update(func(s *QueueUpsert) {
		s.UpdateArchiveChat()
	})
}

// ClearArchiveChat clears the value of the "archive_chat" field.
func (u *QueueUpsertBulk) ClearArchiveChat() *QueueUpsertBulk {
	return u.Update(func(s *QueueUpsert) {
		s.ClearArchiveChat()
	})
}

// SetRenderChat sets the "render_chat" field.
func (u *QueueUpsertBulk) SetRenderChat(v bool) *QueueUpsertBulk {
	return u.Update(func(s *QueueUpsert) {
		s.SetRenderChat(v)
	})
}

// UpdateRenderChat sets the "render_chat" field to the value that was provided on create.
func (u *QueueUpsertBulk) UpdateRenderChat() *QueueUpsertBulk {
	return u.Update(func(s *QueueUpsert) {
		s.UpdateRenderChat()
	})
}

// ClearRenderChat clears the value of the "render_chat" field.
func (u *QueueUpsertBulk) ClearRenderChat() *QueueUpsertBulk {
	return u.Update(func(s *QueueUpsert) {
		s.ClearRenderChat()
	})
}

// SetWorkflowID sets the "workflow_id" field.
func (u *QueueUpsertBulk) SetWorkflowID(v string) *QueueUpsertBulk {
	return u.Update(func(s *QueueUpsert) {
		s.SetWorkflowID(v)
	})
}

// UpdateWorkflowID sets the "workflow_id" field to the value that was provided on create.
func (u *QueueUpsertBulk) UpdateWorkflowID() *QueueUpsertBulk {
	return u.Update(func(s *QueueUpsert) {
		s.UpdateWorkflowID()
	})
}

// ClearWorkflowID clears the value of the "workflow_id" field.
func (u *QueueUpsertBulk) ClearWorkflowID() *QueueUpsertBulk {
	return u.Update(func(s *QueueUpsert) {
		s.ClearWorkflowID()
	})
}

// SetWorkflowRunID sets the "workflow_run_id" field.
func (u *QueueUpsertBulk) SetWorkflowRunID(v string) *QueueUpsertBulk {
	return u.Update(func(s *QueueUpsert) {
		s.SetWorkflowRunID(v)
	})
}

// UpdateWorkflowRunID sets the "workflow_run_id" field to the value that was provided on create.
func (u *QueueUpsertBulk) UpdateWorkflowRunID() *QueueUpsertBulk {
	return u.Update(func(s *QueueUpsert) {
		s.UpdateWorkflowRunID()
	})
}

// ClearWorkflowRunID clears the value of the "workflow_run_id" field.
func (u *QueueUpsertBulk) ClearWorkflowRunID() *QueueUpsertBulk {
	return u.Update(func(s *QueueUpsert) {
		s.ClearWorkflowRunID()
	})
}

// SetUpdatedAt sets the "updated_at" field.
func (u *QueueUpsertBulk) SetUpdatedAt(v time.Time) *QueueUpsertBulk {
	return u.Update(func(s *QueueUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *QueueUpsertBulk) UpdateUpdatedAt() *QueueUpsertBulk {
	return u.Update(func(s *QueueUpsert) {
		s.UpdateUpdatedAt()
	})
}

// Exec executes the query.
func (u *QueueUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the QueueCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for QueueCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *QueueUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
